<?php

use App\ProjectOrderer;
use Illuminate\Database\Seeder;

/**
 * 元請け情報のSeeder
 */
class ProjectOrderersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'わ株式会社',
            'company_kana'   => 'ワカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => null,
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'や株式会社',
            'company_kana'   => 'ヤカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'あ株式会社',
            'company_kana'   => 'アカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'く株式会社',
            'company_kana'   => 'クカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'あい株式会社',
            'company_kana'   => 'アイカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'user_id'        => '1',
            'company'        => 'ス株式会社',
            'company_kana'   => 'スカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '都株式会社',
            'company_kana'   => 'トカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '株式会社テスト建設',
            'company_kana'   => 'カブシキガイシャテストケンセツ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '株式会社テスト',
            'company_kana'   => 'カブシキガイシャテスト',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '有限会社山田',
            'company_kana'   => 'ユウゲンガイシャヤマダ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'わ株式会社',
            'company_kana'   => 'ワカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'や株式会社',
            'company_kana'   => 'ヤカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'あ株式会社',
            'company_kana'   => 'アカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'く株式会社',
            'company_kana'   => 'クカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'あい株式会社',
            'company_kana'   => 'アイカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'user_id'        => '1',
            'company'        => 'ス株式会社',
            'company_kana'   => 'スカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '都株式会社',
            'company_kana'   => 'トカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '株式会社テスト建設',
            'company_kana'   => 'カブシキガイシャテストケンセツ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '株式会社テスト',
            'company_kana'   => 'カブシキガイシャテスト',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '有限会社山田',
            'company_kana'   => 'ユウゲンガイシャヤマダ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'わ株式会社',
            'company_kana'   => 'ワカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'や株式会社',
            'company_kana'   => 'ヤカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'あ株式会社',
            'company_kana'   => 'アカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'く株式会社',
            'company_kana'   => 'クカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'あい株式会社',
            'company_kana'   => 'アイカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'user_id'        => '1',
            'company'        => 'ス株式会社',
            'company_kana'   => 'スカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '都株式会社',
            'company_kana'   => 'トカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '株式会社テスト建設',
            'company_kana'   => 'カブシキガイシャテストケンセツ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '株式会社テスト',
            'company_kana'   => 'カブシキガイシャテスト',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '有限会社山田',
            'company_kana'   => 'ユウゲンガイシャヤマダ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'わ株式会社',
            'company_kana'   => 'ワカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'や株式会社',
            'company_kana'   => 'ヤカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'あ株式会社',
            'company_kana'   => 'アカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'く株式会社',
            'company_kana'   => 'クカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => 'あい株式会社',
            'company_kana'   => 'アイカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'user_id'        => '1',
            'company'        => 'ス株式会社',
            'company_kana'   => 'スカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '都株式会社',
            'company_kana'   => 'トカブシキガイシャ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '株式会社テスト建設',
            'company_kana'   => 'カブシキガイシャテストケンセツ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '株式会社テスト',
            'company_kana'   => 'カブシキガイシャテスト',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);
        ProjectOrderer::create([
            'user_id'        => '1',
            'company'        => '有限会社山田',
            'company_kana'   => 'ユウゲンガイシャヤマダ',
            'zip'            => '0001111',
            'address'        => '東京都千代田区千代田1-1-1 千代田ビルディング1F',
            'president'      => '山田太郎',
            'president_kana' => 'ヤマダタロウ',
            'tel'            => '0300001111',
            'fax'            => '0300002222',
            'phone'          => '08011112222',
            'email'          => 'test@testcompany.com',
            'remark'         => '備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考備考',
        ]);

    }
}
